#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;

use lib 'lib';
use WWW::Dailymotion::Download;

my $home =$ENV{HOME};
my $pwd = $ENV{PWD};

my $help;
my $version = 0;
my $destination;
my $quiet;
my $get_url;
my $title;
my $title_of_the_page;

my $found = 0;

GetOptions (
	"h|help"	=> \$help,
	"v|version"	=> \$version,
	"o|output=s"	=> \$destination,
	"q|quiet"	=> \$quiet,
	"t|title"	=> \$title,
	"g|get-url"	=> \$get_url
);

my ($url) = @ARGV;


if (  (!defined($url)) and 
	(!defined($help))and 
	(!defined($destination))and
	(!defined($quiet))and
	(!defined($title))and
	(!defined($get_url))and
	(($version eq 1)) 
    ){
die "$WWW::Dailymotion::Download::VERSION\n";
}



elsif ((!defined($url)) or (defined($help)) ) {
die "
usage: dailymotion-dl [options] video_url

options:
  -h, --help            print this help text and exit
  -v, --version         print program version and exit

  -o FILE, --output=FILE
                        output video file name
  -q, --quiet           activates quiet mode
  -t, --title           use title in file name
  -g, --get-url         print final video URL only
";
}


my $wdd = WWW::Dailymotion::Download->new( debug => 1 );
for my $url (@ARGV){
	print "Downloading $url\n";
	$wdd->download($url);
}

=pod

=head1 NAME

dailymotion-dl - a script to download videos from Dailymotion

=head1 DESCRIPTION

This script is a command line script similar to the python script youtube-dl that downloads from youtube

=head1 README

This script is a command line script similar to the python script youtube-dl that downloads from youtube

=head1 AUTHOR

CPAN ~GNUTOO.

=head1 LICENSE

GNU GPL 3.

=cut
