#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;

use lib 'lib';
use WWW::Dailymotion::Download;

my $home =$ENV{HOME};
my $pwd = $ENV{PWD};

my $help;
my $version = 0;
my $destination;
my $quiet;
my $get_url;
my $title;
my $title_of_the_page;

my $found = 0;

GetOptions (
	"h|help"	=> \$help,
	"v|version"	=> \$version,
	"o|output=s"	=> \$destination,
	"q|quiet"	=> \$quiet,
	"t|title"	=> \$title,
	"g|get-url"	=> \$get_url
);

my ($url) = @ARGV;


if (  (!defined($url)) and 
	(!defined($help))and 
	(!defined($destination))and
	(!defined($quiet))and
	(!defined($title))and
	(!defined($get_url))and
	(($version eq 1)) 
    ){
die "$WWW::Dailymotion::Download::VERSION\n";
}



elsif ((!defined($url)) or (defined($help)) ) {
die "
usage: dailymotion-download <video_url>

options:
  -h, --help            print this help text and exit
  -v, --version         print program version and exit
";
}


my $wdd = WWW::Dailymotion::Download->new( debug => 1 );
for my $url (@ARGV){
	print "Downloading $url\n";
	$wdd->download($url);
}

=pod

=head1 NAME

dailymotion-download - command-line script to download videos from Dailymotion

=head1 SYNOPSIS

	dailymotion-download <URL>

=head1 DESCRIPTION

Similar to the script being shipped with L<Yuji|http://search.cpan.org/~xaicron/>)'s effort
L<WWW::YouTube::Download>, this script is a Perl replacement for what the python based youtube-dl
does: help a user download videos from Dailymotion.com.

=head1 HISTORY

I've found the script L<dailymotion-dl.pl|http://backpan.perl.org/authors/id/G/GN/GNUTOO/dailymotion-dl.pl>
abandoned on CPAN. No user email was to be found, no description, and it had been deleted from CPAN.
The BackPAN had a copy, with the original GNU open source license intact.

=head1 AUTHOR

Originally, CPAN ~GNUTOO.

=head1 LICENSE

GNU GPL 3.

=cut
